### ISSUE TITLE
💡 refactor [structure]: bring all code to the src

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#38]
### Summary

Das Entwickeln einer eigenen Library macht in der Standalone-App wenig Sinn. Wenn wir zu einem späteren Zeitpunkt wieder die Integration ins IPM ins Auge fassen, können wir die entsprechenden Komponenten schnell wieder in ein Library-Project auslagern.

### Tasks / To do

Verschiebe folgende Elemente aus `projects/ingest/src/lib` nach `src/app`
  - [x] converter components `xml2json`
  - [x] models
  - [x] pipes

Die Komponente `xml2json` sollte auseinander genommen werden und in wiederverwendbare Elemente verschoben werden.

**Comment by kilchenmann** [comment]
Wie soll der Code generell strukturiert werden? @janicklg hast Du gute Ideen?

**Comment by janicklg** [comment]
> Wie soll der Code generell strukturiert werden? @janicklg hast Du gute Ideen?

Persönlich würde ich eine Modulare aufbauweise bevorzugen, vielleicht wäre es aber für diese Applikation overkill?
* src
  * app
    * core
      * components
        * footer
          * footer.component.ts / html / scss 
        * header
          * header.component.ts / html / scss 
         * navbar
           * ...
        * page-not-found
          * ... 
      *  constants
         *  global.constants.ts
      * utils 
        * common.util.ts 
    * features
      * feature-a
        * components
          * component a
            * component-a.component.ts / html / scss
          * component b 
            * ... 
        * pages
          * page a
            * page-a.page.ts / html / scss 
          * page b  
            * ... 
        * models
          * foo.model.ts 
        * services 
          * foo.service.ts 
      * feature-b 
        * ... 
    * shared
      * components
        * generic-dialog.component
          *  generic-dialog.component.ts / html / scss  
        * foo
          * ... 
      * directives
        * shared.directive.ts 
      * pipes 
        * shared.pipe.ts 
    * assets
      * i18n
      * images
      * icons 

Angelehnt an Erfahrung & https://itnext.io/choosing-the-right-file-structure-for-angular-in-2020-and-beyond-a53a71f7eb05

**Comment by janicklg** [comment]
Das Auseinandernehmen der 'xml2json' Komponente wird mit #55 erledigt.
