### ISSUE TITLE
💡 feat [export]: open export folder

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#40]
### Summary

Nachdem die AIPs vorbereitet sind erfolgt der Export der Daten. Über einen Export- oder Erstellen-Button wird das Zielverzeichnis mittels File-Explorer ausgewählt. 

### Tasks / To do

- [x] Export Button, der den File-Explorer öffnet
- [x] Rückgabe des Pfades an die App

**Comment by janicklg** [comment]
Vlt könnte der User über `showSaveDialog` ( https://www.electronjs.org/docs/latest/api/dialog) den Filepfad auswählen, bei welchem man dann das File abspeichert.
