### ISSUE TITLE
💡 feat [dialog]: extend dialog component

### ISSUE THREAD

**Issue by janicklg** [av-dimag/ech-0160-dimag-ingest#58]
### Summary

Die Dialog-Komponente soll erweitert werden, da sie aktuell nur eine Message mit einem 'Ok' Button anzeigen kann (vlt. könnte man für das nur 'alert()' benutzen, da es in Electron standardmässig schon einigermassen 'schön' designed ist).

Für das Exportieren / Speichern der Pakete soll nach dem der User einen Pfad ausgewählt hat ein Dialog erscheinen, welchem man einen Text mitgeben kann und dann entweder 'Abbrechen' oder 'Bestätigen' kann. Beim Abbrechen passiert nichts und der User kann seine Pakete anpassen. Beim Bestätigen werden die Pakete im ausgewählten Pfad abgespeichert.

### Tasks / To do

- [x] Überprüfen, ob man für Messages ohne Actions nur 'alert()' aufruft
- [x] Dialog-Komponente erweitern (mit Abbrechen / Bestätigen Action)

**Comment by janicklg** [comment]
@kilchenmann Was denkst du bezüglich dem 'alert()' für Messages ohne Funktionalitäten? In Electron sieht es schöner aus, als im Browser.

**Comment by kilchenmann** [comment]
Von mir aus können wir vorerst die alerts so belassen 👍
