### ISSUE TITLE
🐛 bug [electron]: update electron without breaking application

### ISSUE THREAD

**Issue by janicklg** [av-dimag/ech-0160-dimag-ingest#67]
### Description

Damit wir den 'showOpenDialog' von Electron verwenden können, importieren wir den ElectronService von 'ngx-electron'. Da bei Electron mit Version 14 'Remote' entfernt wurde, aber bei 'ngx-electron' noch exportiert wird, erhalten wir einen Kompilierfehler. Man kann es einfach auskommentieren, aber das ist auch keine gute Lösung. 

Als Quickfix dafür wurde Electron auf die Version 13.6 gedowngradet.

Nun soll man weitere mögliche Lösungen prüfen (z.B eigener ElectronService), um Electron auf dem neusten Stand zu haben und trotzdem den 'showOpenDialog' verwenden zu können.

### Reproduction steps

-

### Environment

Electron

**Comment by kilchenmann** [comment]
ups... da arbeite ich auch gerade daran.

**Comment by janicklg** [comment]
> ups... da arbeite ich auch gerade daran.

Habs nur mal erfasst, aber noch nicht angefangen

**Comment by kilchenmann** [comment]
Ich halbe folgende Lösung in #65 ausprobiert: https://github.com/ThorstenHans/ngx-electron/issues/71#issuecomment-1083468803

**Comment by kilchenmann** [comment]
Hier der Link zum patch-package: https://www.npmjs.com/package/patch-package

Kannst Du @janicklg bei Gelegenheit mal ein Review des PRs #65 machen und schauen, ob das so stimmt. Das README des patch-package ist irgendwie nicht ganz klar. Man könnte auch etwas mit `yarn patch` machen, aber das konnte ich nicht ausprobieren. 

Wichtig ist, dass man nach `yarn install` nun auch `yarn postinstall` ausführt, um eben auch das "gepatchte" Paket zu übernehmen.

**Comment by kilchenmann** [comment]
Bei `ng s` resp. `yarn start` gibt es allerdings noch viele warnings und errors
