### ISSUE TITLE
🚧 refactor [test]: resolve warnings when running yarn test

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#71]
### Summary

Beim Ausführen von `ng test` werden sehr viele Warnungen aufgelistet. Z.T. liegt dies an fehlenden Imports in den spec Files. Deshalb sollte man mal alle spec Files einzeln (mit `fdescribe` und `ng test`) durchgehen, um die Anzahl Warnungen zu minimieren.  

### Tasks / To do

s. Beschreibung oben

**Comment by kilchenmann** [comment]
Habe im Branch [refactor-unit-tests](https://github.com/av-dimag/ech-0160-dimag-ingest/tree/refactor-unit-tests) bereits begonnen.

**Comment by janicklg** [comment]
> Habe im Branch [refactor-unit-tests](https://github.com/av-dimag/ech-0160-dimag-ingest/tree/refactor-unit-tests) bereits begonnen.

Ich bin nun auf deinem Branch an einer Lösung dran.
