### ISSUE TITLE
💡 feat [version]: display version 

### ISSUE THREAD

**Issue by kilchenmann** [av-dimag/ech-0160-dimag-ingest#73]
### Summary

Die Version aus dem Package.json sollte zumindest auf der "Info"-Seite angezeigt werden. 

```
// imports
const { version: appVersion } = require('../../../../package.json');
...
// component
appVersion: string = 'v' + appVersion;
```

### Tasks / To do

- App-Hinweise inkl. Version auf der Info-Seite
- evt. App-Version im Header, um verwendete Version direkt zu sehen.

**Comment by janicklg** [comment]
Beispiel mit Version im Header -> was haltest du davon?  @kilchenmann 
![image](https://user-images.githubusercontent.com/29749311/223074315-1d0da94b-052e-47e7-9c6e-611ef46b4939.png)

**Comment by janicklg** [comment]
@kilchenmann -> wie / wo möchtest du die Version auf der Infopage haben?
